name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-24.04

    environment: publish

    env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}

    steps:
      - name: Authenticate with GitHub App
        id: app-token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}

      - name: Copy README.md
        run: cp README.md lib/README.md

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: lib/node_modules
          key: node-modules-${{ hashFiles('lib/bun.lock') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: lib

      - name: Update package.json version
        run: bun version ${{ github.event.release.tag_name }}

      - name: Commit package.json
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name 'Automated Publisher'
          git config user.email 'automated-publisher[bot]@users.noreply.github.com'
          git add package.json
          git commit -m "Updated package.json version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:main
        working-directory: lib

      - name: Publish
        run: bun publish --access public
        working-directory: lib
